version: '3.8'

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    # network_mode: host
    ports:
      - 5432:5432
    expose:
      - 5432
    volumes:
      - db-data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      PGADMIN_CONFIG_SERVER_MODE: "False"
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: "False"
      PGADMIN_LISTEN_PORT: 8080
    # network_mode: host
    ports:
      - "8080:8080"
    depends_on:
      - db
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    # entrypoint: /bin/sh -c "chmod 600 /pgpass; /entrypoint.sh;"
    # user: root
    # configs:
    #   - source: servers_json
    #     target: /pgadmin4/servers.json
    #   - source: pgpass
    #     target: /pgpass

# configs:
#   pgpass:
#     content: thridwheelerdb:5432:*:myuser:aqerqrqrq
#   servers_json:
#     content: |
#       {
#         "Servers": {
#           "1": {
#             "Group": "Servers",
#             "Name": "My Local Postgres 16.1",
#             "Host": "localhost",
#             "Port": 5432,
#             "MaintenanceDB": "postgres",
#             "Username": "postgres",
#             "PassFile": "/pgpass",
#             "SSLMode": "prefer"
#           }
#         }
#       }

  # bot:
  #   build: .
  #   depends_on:
  #     - db
  #   environment:
  #     - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@localhost:5432/${POSTGRES_DB}
  #     - BOT_TOKEN=${BOT_TOKEN}
  #     - OPENAI_API_KEY=${OPENAI_API_KEY}
  #   volumes:
  #     - .:/app
  #   network_mode: host

volumes:
  db-data:
  pgadmin-data:
