"""Add relationship between User and ScheduledAction

Revision ID: 2bf0ab3dec37
Revises: 582b8e0c36bf
Create Date: 2024-09-01 17:59:04.375856

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2bf0ab3dec37'
down_revision: Union[str, None] = '582b8e0c36bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scheduled_actions', sa.Column('description', sa.Text(), nullable=False))
    op.alter_column('scheduled_actions', 'id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_constraint('scheduled_actions_couple_id_fkey', 'scheduled_actions', type_='foreignkey')
    op.drop_column('scheduled_actions', 'couple_id')
    op.drop_column('scheduled_actions', 'action')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scheduled_actions', sa.Column('action', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('scheduled_actions', sa.Column('couple_id', sa.BIGINT(), autoincrement=False, nullable=True))
    op.create_foreign_key('scheduled_actions_couple_id_fkey', 'scheduled_actions', 'couples', ['couple_id'], ['id'])
    op.alter_column('scheduled_actions', 'id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_column('scheduled_actions', 'description')
    # ### end Alembic commands ###
