"""Make requested_id nullable in PendingCouple and remove invite_token from User

Revision ID: b38799a1728f
Revises: 
Create Date: 2024-09-01 12:43:35.040942

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b38799a1728f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pending_couples', 'requested_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('users', 'invite_token')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('invite_token', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.alter_column('pending_couples', 'requested_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
